name: Android CI


env:
  JAVA_VERSION: 21
  APK_PATH_RELEASE: build/outputs/apk/release/OSS-Dict-release.apk
  APK_PATH_DEBUG: build/outputs/apk/debug/OSS-Dict-debug.apk

on:
  # push:
  #   branches: [ "master42" ]
  # pull_request:
  #   branches: [ "master42" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        fetch-tags: true
        ref: apk-build

    # - name: Update git submodules
    #   run: |
    #     git submodule update --init --recursive --remote

    - name: set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: gradle

    - name: Set TAG env var
      run: |
        RAW=$(git describe --tags --always 2>/dev/null || echo "${{ github.event.repository.name }}")
        CLEAN=$(echo "$RAW" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
        echo "TAG=$CLEAN" >> $GITHUB_ENV
        echo "raw=$RAW" >> $GITHUB_OUTPUT
        echo "clean=$CLEAN" >> $GITHUB_OUTPUT
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build apk debug
      if: false
      run: ./gradlew assembleDebug

    - name: Upload APK Debug - ${{ github.event.repository.name }}
      if: false
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-debug.apk
        path: ${{ env.APK_PATH_DEBUG }}
        
    - name: DEBUG PRINT GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" \
          | base64 --decode > $RUNNER_TEMP/release.keystore
      
    - name: Build Release APK
      env:
        KEYSTORE: ${{ runner.temp }}/release.keystore
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: ./gradlew assembleRelease
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-release.apk
        path: ${{ env.APK_PATH_RELEASE }}

    # - name: Upload Release AAB
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ github.event.repository.name }}-release.aab
    #     path: ${{ env.AAB_PATH_RELEASE }}          
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/heads/android/')
      with:
        tag_name: ${{ env.TAG }}
        files: ${{ env.APK_PATH_RELEASE }}
        # files: ${{ env.APK_PATH_RELEASE }}, ${{ env.AAB_PATH_RELEASE }}
        generate_release_notes: false
        make_latest: true

